title: "Rangana.de"
description: "Personal Website of Rangana Withanage"
production_url: "https://www.rangana.de"
repository: "ranwitter/ranwitter.github.io"
url: "https://www.rangana.de"
logo: "/rangana.png"
theme: jekyll-theme-leap-day
show_downloads: false
google_analytics: 
github:
        is_project_page: true
        repository_name: "ranwitter.github.io"
        owner_url: "https://github.com/ranwitter"
        owner_name: "ranwitter"
        show_generated_by : false
