<<<<<<< HEAD
theme: jekyll-theme-tactile
title: "Rangana Withanage"
description: "Scroll of Technology Adventures"
production_url: "https://www.rangana.de"
repository: "ranwitter/ranwitter.github.io"
url: "https://www.rangana.de"
logo: "/rangana.png"
=======
theme: jekyll-theme-hacker
>>>>>>> origin/master
